apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: demo
    name: demo
    namespace: demo
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: demo
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: demo
      spec:
        containers:
        - env:
          image: ivandal77/demo1
          imagePullPolicy: Always
          name: demo
          ports:
          - containerPort: 3000
            protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
